[2025-08-06T19:37:51.967+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-06T19:37:52.004+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: register_high_latency_model.rollback_model manual__2025-08-06T19:37:34.691667+00:00 [queued]>
[2025-08-06T19:37:52.016+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: register_high_latency_model.rollback_model manual__2025-08-06T19:37:34.691667+00:00 [queued]>
[2025-08-06T19:37:52.017+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-06T19:37:52.039+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): rollback_model> on 2025-08-06 19:37:34.691667+00:00
[2025-08-06T19:37:52.054+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2690) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-06T19:37:52.057+0000] {standard_task_runner.py:63} INFO - Started process 2700 to run task
[2025-08-06T19:37:52.058+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'register_high_latency_model', 'rollback_model', 'manual__2025-08-06T19:37:34.691667+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_model_rollback.py', '--cfg-path', '/tmp/tmp83y5lgw5']
[2025-08-06T19:37:52.062+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask rollback_model
[2025-08-06T19:37:52.129+0000] {task_command.py:426} INFO - Running <TaskInstance: register_high_latency_model.rollback_model manual__2025-08-06T19:37:34.691667+00:00 [running]> on host 36543e3c12b4
[2025-08-06T19:37:52.575+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='register_high_latency_model' AIRFLOW_CTX_TASK_ID='rollback_model' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T19:37:34.691667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T19:37:34.691667+00:00'
[2025-08-06T19:37:52.577+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-06T19:37:53.498+0000] {logging_mixin.py:188} WARNING - 2025/08/06 19:37:53 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-08-06T19:37:53.992+0000] {logging_mixin.py:188} WARNING - 2025/08/06 19:37:53 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
[2025-08-06T19:38:03.795+0000] {logging_mixin.py:188} WARNING - 2025/08/06 19:38:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-08-06T19:38:04.091+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-08-06T19:38:05.329+0000] {logging_mixin.py:188} WARNING - Registered model 'FraudDetectionModel' already exists. Creating a new version of this model...
[2025-08-06T19:38:05.993+0000] {logging_mixin.py:188} WARNING - 2025/08/06 19:38:05 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: FraudDetectionModel, version 4
[2025-08-06T19:38:05.996+0000] {logging_mixin.py:188} WARNING - Created version '4' of model 'FraudDetectionModel'.
[2025-08-06T19:38:09.071+0000] {warnings.py:110} WARNING - /opt/***/dags/test_model_rollback.py:72: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  model_version = client.get_latest_versions("FraudDetectionModel", stages=["None"])[-1]

[2025-08-06T19:38:09.115+0000] {warnings.py:110} WARNING - /opt/***/dags/test_model_rollback.py:73: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(

[2025-08-06T19:38:09.256+0000] {logging_mixin.py:188} INFO - üèÉ View run persistent-dove-734 at: http://mlflow:5000/#/experiments/3/runs/2b595bd38b724a8f841d13406f5fea3f
[2025-08-06T19:38:09.257+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/3
[2025-08-06T19:38:09.290+0000] {logging_mixin.py:188} INFO - üöÄ High latency model version 4 deployed to Production!
[2025-08-06T19:38:09.291+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-06T19:38:09.292+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-06T19:38:09.304+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=register_high_latency_model, task_id=rollback_model, run_id=manual__2025-08-06T19:37:34.691667+00:00, execution_date=20250806T193734, start_date=20250806T193752, end_date=20250806T193809
[2025-08-06T19:38:09.376+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-06T19:38:09.396+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-06T19:38:09.398+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
