[2025-08-14T23:38:55.796+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T23:38:55.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-14T23:38:53.163318+00:00 [queued]>
[2025-08-14T23:38:55.968+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-14T23:38:53.163318+00:00 [queued]>
[2025-08-14T23:38:56.004+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-14T23:38:56.077+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): preprocess_dvc> on 2025-08-14 23:38:53.163318+00:00
[2025-08-14T23:38:56.100+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'preprocess_dvc', 'manual__2025-08-14T23:38:53.163318+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmpq3oigmhz']
[2025-08-14T23:38:56.106+0000] {standard_task_runner.py:91} INFO - Job 217: Subtask preprocess_dvc
[2025-08-14T23:38:56.103+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=337) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-14T23:38:56.109+0000] {standard_task_runner.py:63} INFO - Started process 338 to run task
[2025-08-14T23:38:56.305+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-14T23:38:53.163318+00:00 [running]> on host 1ff62addae83
[2025-08-14T23:38:56.625+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='preprocess_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T23:38:53.163318+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T23:38:53.163318+00:00'
[2025-08-14T23:38:56.626+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T23:38:56.667+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T23:38:56.669+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /opt/***/ml_pipeline\n        dvc pull data/raw.dvc \n        dvc repro preprocess\n        dvc push\n        ']
[2025-08-14T23:38:56.688+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T23:39:08.310+0000] {subprocess.py:93} INFO - ERROR: failed to connect to s3 (mlflow-artifacts/files/md5) - Could not connect to the endpoint URL: "http://localhost:9000/mlflow-artifacts/files/md5"
[2025-08-14T23:39:08.311+0000] {subprocess.py:93} INFO - ERROR: failed to pull data from the cloud - 3 files failed to download
[2025-08-14T23:39:11.858+0000] {subprocess.py:93} INFO - 'data/raw.dvc' didn't change, skipping
[2025-08-14T23:39:12.048+0000] {subprocess.py:93} INFO - Running stage 'preprocess':
[2025-08-14T23:39:12.049+0000] {subprocess.py:93} INFO - > python preprocessing/preprocess_task.py
[2025-08-14T23:39:15.263+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T23:39:15.264+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/preprocessing/preprocess_task.py", line 26, in <module>
[2025-08-14T23:39:15.265+0000] {subprocess.py:93} INFO -     with open("version_meta.json", 'r') as f:
[2025-08-14T23:39:15.265+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-14T23:39:15.266+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'version_meta.json'
[2025-08-14T23:39:15.609+0000] {subprocess.py:93} INFO - ERROR: failed to reproduce 'preprocess': failed to run: python preprocessing/preprocess_task.py, exited with 1
[2025-08-14T23:39:19.118+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-08-14T23:39:19.586+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-14T23:39:19.593+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T23:39:19.684+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ml_pipeline_dvc, task_id=preprocess_dvc, run_id=manual__2025-08-14T23:38:53.163318+00:00, execution_date=20250814T233853, start_date=20250814T233855, end_date=20250814T233919
[2025-08-14T23:39:19.788+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-14T23:39:19.854+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T23:39:19.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
